template_path: templates/backbone.json

parameters:
  ProductName: appclustermin
  EnvironmentName: dev
  VpcCIDR: 10.0.0.0/16
  PublicSubnet1CIDR: 10.0.30.0/24
  PublicSubnet2CIDR: 10.0.40.0/24
  PrivateSubnet1CIDR: 10.0.31.0/24
  PrivateSubnet2CIDR: 10.0.41.0/24
