template_path: templates/redis.json
parameters:
  ProductName: vdmscluster
  EnvironmentName: ops
  VpcId: vpc-0d4dd67070467ba70
  SubnetA: ["subnet-0e7ddd689d30aedca"]
  SubnetB: ["subnet-00a66c2491c74dc4a"]
  ClusterName: "redistesting"