template_path: templates/xformation.json
parameters:
  ProductName: !stack_output backbone::ProductName
  EnvironmentName: !stack_output backbone::EnvironmentName
  VPC:  !stack_output backbone::VPC
  Cluster: !stack_output ecscluster::Cluster
  Listener: !stack_output loadbalancer::Listener
  LoadbalancerUrl:  !stack_output loadbalancer::LoadBalancerUrl
  DBHost:  !stack_output rds::DbUrl
  DBUser: postgres
  DBPassword: postgres
  DBJdbcUrl: !stack_output rds::JDBCConnectionStringPrefix
  
