template_path: templates/rdgw.json

parameters:
  # VpcCIDR: 172.16.0.0/16
  # PublicSubnet1CIDR: 172.16.0.0/24
  # PublicSubnet2CIDR: 172.16.1.0/24
  # PublicSubnet3CIDR: 172.16.2.0/24
  # PrivateSubnet1CIDR: 172.16.3.0/24
  # PrivateSubnet2CIDR: 172.16.4.0/24
  # PrivateSubnet3CIDR: 172.16.5.0/24
  KeyPairName: testingserverkeypair
  DomainAdminPassword: Nhy6Mju7
  VPCID: vpc-0d4dd67070467ba70
  RDGWCIDR: 10.0.0.0/24
  PublicSubnet1ID: subnet-0e7ddd689d30aedca
  DomainMemberSGID: sg-02caa2a98295da16d
  PublicSubnet2ID: subnet-0c9a3e1ffa14ccd2d