template_path: templates/rdgw.json

parameters:
  KeyPairName: testingserverkeypair
  DomainAdminPassword: Nhy6Mju7
  VpcId: !stack_output backbone::VPC
  RDGWCIDR: 0.0.0.0/0
  PublicSubnet1ID: !stack_output backbone::PublicSubnet1
  DomainMemberSGID: sg-0384ad238f1d1f746
  PublicSubnet2ID: !stack_output backbone::PublicSubnet2
  PublicSubnet3ID: !stack_output backbone::PublicSubnet3
  QSS3BucketName: ocregistryoc
  DomainDNSName: scloud.com
  DomainNetBIOSName: SCLOUD
  DomainAdminUser: salam
  DomainAdminPassword: Nhy6Mju7
  #QSS3KeyPrefix: quickstart-microsoft-utilities