template_path: templates/rdgw.json

parameters:
  KeyPairName: testingserverkeypair
  DomainAdminPassword: Nhy6Mju7
  VpcId: vpc-0d4dd67070467ba70
  RDGWCIDR: 0.0.0.0/0
  PublicSubnet1ID: subnet-0e7ddd689d30aedca
  DomainMemberSGID: sg-02caa2a98295da16d
  PublicSubnet2ID: subnet-0c9a3e1ffa14ccd2d
  QSS3BucketName: ocregistryoc
  DomainDNSName: scloud.com
  DomainNetBIOSName: SCLOUD
  DomainAdminUser: salam
  DomainAdminPassword: Nhy6Mju7
  #QSS3KeyPrefix: quickstart-microsoft-utilities