template_path: templates/rdgw.json

parameters:
  KeyPairName: #Enter Key Pair Name
  VpcId: !stack_output backbone::VPC
  RDGWCIDR: 0.0.0.0/0
  PublicSubnet1ID: !stack_output backbone::PublicSubnet1
  DomainMemberSGID: !stack_output securitygroups::DomainMemberSGID
  PublicSubnet2ID: !stack_output backbone::PublicSubnet2
  PublicSubnet3ID: !stack_output backbone::PublicSubnet3
  QSS3BucketName: ocregistryoc
  DomainDNSName: #Enter Domain name --> example.com
  DomainNetBIOSName: # Enter NetBios name --> EXAMPLE
  DomainAdminUser: # Domain user name
  DomainAdminPassword: # Domain USer Password
  #QSS3KeyPrefix: quickstart-microsoft-utilities