template_path: templates/vpn.json
parameters:
  EnvironmentName: !stack_output backbone::EnvironmentName
  # ProductName: !stack_output backbone::ProductName
  VpcId:  !stack_output backbone::VPC
  # WhitelistIP: 0.0.0.0/0
  IpAddressUS: #Firewall IP to create a VPN endpoint ex: 100.69.7.221
  IpAddressUK: #Firewall IP to create a VPN endpoint ex: 100.69.4.131