template_path: templates/vpn.json
parameters:
  EnvironmentName: !stack_output backbone::EnvironmentName
  # ProductName: !stack_output backbone::ProductName
  VpcId:  !stack_output backbone::VPC
  # WhitelistIP: 0.0.0.0/0
  IpAddressUS: 100.64.3.221
  IpAddressUK: 100.64.3.231