template_path: templates/nginx.json
parameters:
  ProductName: !stack_output backbone::ProductName
  EnvironmentName: !stack_output backbone::EnvironmentName
  VPC:  !stack_output backbone::VPC
  Cluster: !stack_output ecscluster::Cluster
  HttpsListener: !stack_output loadbalancer::Listener
  HttpListener: !stack_output loadbalancer::HttpListener
  LoadbalancerUrl:  !stack_output loadbalancer::LoadBalancerUrl