# template_path: templates/vpn.json
# parameters:
#   EnvironmentName: !stack_output backbone::EnvironmentName
#   # ProductName: !stack_output backbone::ProductName
#   VpcId:  !stack_output backbone::VPC
#   # WhitelistIP: 0.0.0.0/0
#   IpAddressUS: <FireWall IP>
#   IpAddressUK: <FireWall IP>