template_path: templates/rdgw.json

parameters:
  KeyPairName: pingtest_keypair
  DomainAdminPassword: 8293Kwr64jR%
  VpcId: !stack_output backbone::VPC
  RDGWCIDR: 0.0.0.0/0
  PublicSubnet1ID: !stack_output backbone::PublicSubnet1
  DomainMemberSGID: !stack_output securitygroups::DomainMemberSGID
  PublicSubnet2ID: !stack_output backbone::PublicSubnet2
  QSS3BucketName: ocregistryoc
  DomainDNSName: argusrg.com
  DomainNetBIOSName: ARGUSRG
  DomainAdminUser: aws_service
  #QSS3KeyPrefix: quickstart-microsoft-utilities