template_path: templates/terminal.json

parameters:
  KeyPairName: argus-key
  VpcId: !stack_output backbone::VPC
  terminalCIDR: 0.0.0.0/0
  PublicSubnet1ID: !stack_output backbone::PrivateSubnet1
  DomainMemberSGID: !stack_output securitygroups::DomainMemberSGID
  PublicSubnet2ID: !stack_output backbone::PrivateSubnet2
  PublicSubnet3ID: !stack_output backbone::PrivateSubnet3
  QSS3BucketName: ocregistryoc
  DomainDNSName: argusrg.com
  DomainNetBIOSName: ARGUSRG
  DomainAdminUser: #Domain user Name
  DomainAdminPassword: #Password
  #QSS3KeyPrefix: quickstart-microsoft-utilities